In [1]:
import numpy as np
import torch

In [2]:
SEED = 1234
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

# Creating Tensors

In [13]:
x = torch.randn(2, 3)

In [14]:
print(f"Type: {x.type()}")
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[-0.0098, -1.4473, -0.2039],
        [ 0.8738, -0.6816,  0.6339]])


In [15]:
x = torch.zeros(3, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# List/NpArray to Tensors

In [16]:
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
x = torch.Tensor(np.random.rand(2, 3))
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [18]:
# Changing tensor type
x = torch.Tensor(3, 4)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


# Operations

In [20]:
# Add
x = torch.randn(2,3)
y = torch.randn(2,3)
print(x)
print(y)

tensor([[ 0.8042, -0.1383,  0.3196],
        [-1.0187, -1.3147,  2.5228]])
tensor([[ 0.4501,  0.2709, -0.8087],
        [-0.0217, -1.0413,  0.0702]])


In [21]:
z = x + y
print(z)

tensor([[ 1.2543,  0.1326, -0.4892],
        [-1.0404, -2.3561,  2.5930]])


In [22]:
# Dot product
x = torch.randn(2,3)
y = torch.randn(3,2)
print(x)
print(y)

tensor([[ 0.5797, -0.0599,  0.1816],
        [-0.6797, -0.2567, -1.8189]])
tensor([[0.2111, 0.3372],
        [0.6638, 1.0397],
        [1.8434, 0.6588]])


In [26]:
# matmul
z = torch.mm(x,y)
print(z.shape)
print(z)

torch.Size([2, 2])
tensor([[ 0.4173,  0.2528],
        [-3.6668, -1.6944]])


In [29]:
# transpose
print(z.T)
print(torch.t(z))

tensor([[ 0.4173, -3.6668],
        [ 0.2528, -1.6944]])
tensor([[ 0.4173, -3.6668],
        [ 0.2528, -1.6944]])


In [32]:
# reshape
print(z)
print(z.view(1,4))

tensor([[ 0.4173,  0.2528],
        [-3.6668, -1.6944]])
tensor([[ 0.4173,  0.2528, -3.6668, -1.6944]])


In [35]:
# Dimensional operation
x = torch.randn(2,3)
print(x)
# Sum columns
y = torch.sum(x, dim=0)
print(y)
# sum rows
z = torch.sum(x, dim=1)
print(z)

tensor([[ 0.5548, -0.0845,  0.5903],
        [-1.0032, -1.7873,  0.0538]])
tensor([-0.4484, -1.8718,  0.6441])
tensor([ 1.0607, -2.7367])


# Indexing

In [38]:
x = torch.randn(3, 4)
print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:2, 1:4]}")

x: 
tensor([[-1.5864, -0.2671,  2.6874, -0.4633],
        [ 0.6639,  0.2383,  0.8305, -0.0838],
        [ 0.9523,  0.2016, -0.1714, -0.8164]])
x[:1]: 
tensor([[-1.5864, -0.2671,  2.6874, -0.4633]])
x[:1, 1:3]: 
tensor([[-0.2671,  2.6874, -0.4633],
        [ 0.2383,  0.8305, -0.0838]])


# Slicing

In [45]:
col_indices = torch.LongTensor([2,0])
selected = torch.index_select(x, dim=0,index = col_indices)
print(selected)

tensor([[ 0.9523,  0.2016, -0.1714, -0.8164],
        [-1.5864, -0.2671,  2.6874, -0.4633]])


# joining

In [46]:
print(x.shape)

torch.Size([3, 4])


In [53]:
print(torch.cat([x,x], dim=0))
print(torch.cat([x,x], dim=1))

tensor([[-1.5864, -0.2671,  2.6874, -0.4633],
        [ 0.6639,  0.2383,  0.8305, -0.0838],
        [ 0.9523,  0.2016, -0.1714, -0.8164],
        [-1.5864, -0.2671,  2.6874, -0.4633],
        [ 0.6639,  0.2383,  0.8305, -0.0838],
        [ 0.9523,  0.2016, -0.1714, -0.8164]])
tensor([[-1.5864, -0.2671,  2.6874, -0.4633, -1.5864, -0.2671,  2.6874, -0.4633],
        [ 0.6639,  0.2383,  0.8305, -0.0838,  0.6639,  0.2383,  0.8305, -0.0838],
        [ 0.9523,  0.2016, -0.1714, -0.8164,  0.9523,  0.2016, -0.1714, -0.8164]])


In [57]:
print(torch.stack([x,x], dim=0))
print(torch.stack([x,x], dim=1))

tensor([[[-1.5864, -0.2671,  2.6874, -0.4633],
         [ 0.6639,  0.2383,  0.8305, -0.0838],
         [ 0.9523,  0.2016, -0.1714, -0.8164]],

        [[-1.5864, -0.2671,  2.6874, -0.4633],
         [ 0.6639,  0.2383,  0.8305, -0.0838],
         [ 0.9523,  0.2016, -0.1714, -0.8164]]])
tensor([[[-1.5864, -0.2671,  2.6874, -0.4633],
         [-1.5864, -0.2671,  2.6874, -0.4633]],

        [[ 0.6639,  0.2383,  0.8305, -0.0838],
         [ 0.6639,  0.2383,  0.8305, -0.0838]],

        [[ 0.9523,  0.2016, -0.1714, -0.8164],
         [ 0.9523,  0.2016, -0.1714, -0.8164]]])


# Gradients
- Gradients (rate of change) of our tensors with respect to their constituents using gradient bookkeeping.
- The gradient is a vector that points in the direction of greatest increase of a function.

In [58]:
x = torch.randn(3,4,requires_grad = True)
y = 3*x+2

print(x.type(), y.type())
print(x)

print(y)

torch.FloatTensor torch.FloatTensor
tensor([[-0.6066, -0.4800,  1.1733,  0.3714],
        [-2.3531, -1.6705, -0.4716,  0.8130],
        [-0.4171, -2.3476,  1.9083, -1.8304]], requires_grad=True)
tensor([[ 0.1803,  0.5599,  5.5200,  3.1143],
        [-5.0593, -3.0116,  0.5853,  4.4391],
        [ 0.7487, -5.0427,  7.7248, -3.4912]], grad_fn=<AddBackward0>)


In [59]:
z = y.mean()
print(z)
z.backward()
print(z)

tensor(0.5223, grad_fn=<MeanBackward0>)
tensor(0.5223, grad_fn=<MeanBackward0>)


In [60]:
print(x.grad)

tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


# CUDA

In [61]:
print (torch.cuda.is_available())

False


In [62]:

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

cpu


In [63]:
x = torch.rand(2,3)
print (x.is_cuda)
x = torch.rand(2,3).to(device) # Tensor is stored on the GPU
print (x.is_cuda)

False
False
